add_test([=[CharMappingChar.LowercaseRuToEn]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingChar.LowercaseRuToEn]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingChar.LowercaseRuToEn]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingChar.LowercaseEnToRu]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingChar.LowercaseEnToRu]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingChar.LowercaseEnToRu]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingChar.UppercaseRuToEn]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingChar.UppercaseRuToEn]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingChar.UppercaseRuToEn]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingChar.UppercaseEnToRu]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingChar.UppercaseEnToRu]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingChar.UppercaseEnToRu]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingChar.NoMappingPassthrough]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingChar.NoMappingPassthrough]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingChar.NoMappingPassthrough]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingChar.YoUppercase]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingChar.YoUppercase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingChar.YoUppercase]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingWord.SwapRussianWordToEnglish]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingWord.SwapRussianWordToEnglish]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingWord.SwapRussianWordToEnglish]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingWord.SwapEnglishWordToRussian]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingWord.SwapEnglishWordToRussian]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingWord.SwapEnglishWordToRussian]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingWord.SwapTitleCase]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingWord.SwapTitleCase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingWord.SwapTitleCase]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingWord.SwapAllCaps]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingWord.SwapAllCaps]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingWord.SwapAllCaps]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingWord.DoubleSwapIsIdentity]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingWord.DoubleSwapIsIdentity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingWord.DoubleSwapIsIdentity]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingWord.DoubleSwapEnglish]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingWord.DoubleSwapEnglish]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingWord.DoubleSwapEnglish]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingWord.YoCharacter]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingWord.YoCharacter]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingWord.YoCharacter]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingWord.HardSign]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingWord.HardSign]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingWord.HardSign]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingWord.NonLettersPassThrough]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingWord.NonLettersPassThrough]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingWord.NonLettersPassThrough]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingLayout.DetectRussian]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingLayout.DetectRussian]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingLayout.DetectRussian]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingLayout.DetectEnglish]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingLayout.DetectEnglish]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingLayout.DetectEnglish]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CharMappingLayout.DetectMixed]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=CharMappingLayout.DetectMixed]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CharMappingLayout.DetectMixed]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WordBoundary.SpaceIsBoundary]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=WordBoundary.SpaceIsBoundary]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WordBoundary.SpaceIsBoundary]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WordBoundary.PunctIsBoundary]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=WordBoundary.PunctIsBoundary]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WordBoundary.PunctIsBoundary]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WordBoundary.LetterIsNotBoundary]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=WordBoundary.LetterIsNotBoundary]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WordBoundary.LetterIsNotBoundary]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapLastWord.SimpleEnglishWord]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapLastWord.SimpleEnglishWord]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapLastWord.SimpleEnglishWord]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapLastWord.SimpleRussianWord]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapLastWord.SimpleRussianWord]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapLastWord.SimpleRussianWord]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapLastWord.WordAfterSpace]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapLastWord.WordAfterSpace]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapLastWord.WordAfterSpace]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapLastWord.WordAfterBoundaryChar]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapLastWord.WordAfterBoundaryChar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapLastWord.WordAfterBoundaryChar]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapLastWord.TextEndsWithBoundary]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapLastWord.TextEndsWithBoundary]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapLastWord.TextEndsWithBoundary]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapLastWord.CursorAtStart]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapLastWord.CursorAtStart]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapLastWord.CursorAtStart]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapLastWord.OnlyBoundaryChars]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapLastWord.OnlyBoundaryChars]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapLastWord.OnlyBoundaryChars]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapLastWord.NoMappableChars]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapLastWord.NoMappableChars]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapLastWord.NoMappableChars]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapLastWord.HyphenInWord]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapLastWord.HyphenInWord]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapLastWord.HyphenInWord]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapSelection.BasicSelection]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapSelection.BasicSelection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapSelection.BasicSelection]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapSelection.MultiWordSelection]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapSelection.MultiWordSelection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapSelection.MultiWordSelection]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapSelection.EmptySelection]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapSelection.EmptySelection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapSelection.EmptySelection]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapSelection.UppercasePreserved]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapSelection.UppercasePreserved]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapSelection.UppercasePreserved]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapRoundTrip.RussianWords]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapRoundTrip.RussianWords]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapRoundTrip.RussianWords]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SwapRoundTrip.EnglishWords]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=SwapRoundTrip.EnglishWords]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SwapRoundTrip.EnglishWords]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.EnglishGarbageFromRussianWord]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.EnglishGarbageFromRussianWord]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.EnglishGarbageFromRussianWord]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.RealEnglishWordNotSwitched]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.RealEnglishWordNotSwitched]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.RealEnglishWordNotSwitched]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.RealEnglishWordThe]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.RealEnglishWordThe]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.RealEnglishWordThe]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.RealRussianWordNotSwitched]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.RealRussianWordNotSwitched]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.RealRussianWordNotSwitched]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.ShortWordIgnored]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.ShortWordIgnored]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.ShortWordIgnored]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.DisabledNeverSwitches]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.DisabledNeverSwitches]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.DisabledNeverSwitches]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.NumberGuard]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.NumberGuard]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.NumberGuard]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.EmailGuard]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.EmailGuard]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.EmailGuard]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.UrlGuard]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.UrlGuard]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.UrlGuard]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.HighThresholdPreventsSwitch]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.HighThresholdPreventsSwitch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.HighThresholdPreventsSwitch]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Heuristic.LowThresholdAllowsSwitch]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Heuristic.LowThresholdAllowsSwitch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Heuristic.LowThresholdAllowsSwitch]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BigramScore.EnglishCommonBigrams]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=BigramScore.EnglishCommonBigrams]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BigramScore.EnglishCommonBigrams]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BigramScore.RussianCommonBigrams]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=BigramScore.RussianCommonBigrams]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BigramScore.RussianCommonBigrams]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BigramScore.GarbageScoresLow]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=BigramScore.GarbageScoresLow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BigramScore.GarbageScoresLow]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Guard.PureLettersNotGuarded]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Guard.PureLettersNotGuarded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Guard.PureLettersNotGuarded]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Guard.DigitsGuarded]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Guard.DigitsGuarded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Guard.DigitsGuarded]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Guard.AtSignGuarded]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Guard.AtSignGuarded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Guard.AtSignGuarded]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Guard.UrlGuarded]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=Guard.UrlGuarded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Guard.UrlGuarded]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ManualQA.ChecklistDocumented]=]  /home/i/PUNTO/_build/tests/punto-tests [==[--gtest_filter=ManualQA.ChecklistDocumented]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ManualQA.ChecklistDocumented]=]  PROPERTIES WORKING_DIRECTORY /home/i/PUNTO/_build/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  punto-tests_TESTS CharMappingChar.LowercaseRuToEn CharMappingChar.LowercaseEnToRu CharMappingChar.UppercaseRuToEn CharMappingChar.UppercaseEnToRu CharMappingChar.NoMappingPassthrough CharMappingChar.YoUppercase CharMappingWord.SwapRussianWordToEnglish CharMappingWord.SwapEnglishWordToRussian CharMappingWord.SwapTitleCase CharMappingWord.SwapAllCaps CharMappingWord.DoubleSwapIsIdentity CharMappingWord.DoubleSwapEnglish CharMappingWord.YoCharacter CharMappingWord.HardSign CharMappingWord.NonLettersPassThrough CharMappingLayout.DetectRussian CharMappingLayout.DetectEnglish CharMappingLayout.DetectMixed WordBoundary.SpaceIsBoundary WordBoundary.PunctIsBoundary WordBoundary.LetterIsNotBoundary SwapLastWord.SimpleEnglishWord SwapLastWord.SimpleRussianWord SwapLastWord.WordAfterSpace SwapLastWord.WordAfterBoundaryChar SwapLastWord.TextEndsWithBoundary SwapLastWord.CursorAtStart SwapLastWord.OnlyBoundaryChars SwapLastWord.NoMappableChars SwapLastWord.HyphenInWord SwapSelection.BasicSelection SwapSelection.MultiWordSelection SwapSelection.EmptySelection SwapSelection.UppercasePreserved SwapRoundTrip.RussianWords SwapRoundTrip.EnglishWords Heuristic.EnglishGarbageFromRussianWord Heuristic.RealEnglishWordNotSwitched Heuristic.RealEnglishWordThe Heuristic.RealRussianWordNotSwitched Heuristic.ShortWordIgnored Heuristic.DisabledNeverSwitches Heuristic.NumberGuard Heuristic.EmailGuard Heuristic.UrlGuard Heuristic.HighThresholdPreventsSwitch Heuristic.LowThresholdAllowsSwitch BigramScore.EnglishCommonBigrams BigramScore.RussianCommonBigrams BigramScore.GarbageScoresLow Guard.PureLettersNotGuarded Guard.DigitsGuarded Guard.AtSignGuarded Guard.UrlGuarded ManualQA.ChecklistDocumented)
